---
- name: Install NodeJS
 become: yes
 hosts: all
 tasks:
    - name: Install Node js
       ansible.builtin.apt:
       name: nodejs npm
       state: Present
       update_cache: yes
---